import {
    ArrowDownFromLine,
    ArrowRightLeft,
    ArrowUpFromLine,
    BookOpenText,
    Check,
    ChevronsUpDown,
    File,
    Group,
    LayoutDashboard,
    Loader2,
    LogOut,
    Menu,
    Search,
    User,
    Users,
    X,
} from "lucide-react";

export const Icons = {
    layoutDashboard: LayoutDashboard,
    group: Group,
    users: Users,
    books: BookOpenText,
    menu: Menu,
    x: X,
    user: User,
    logOut: LogOut,
    loader2: Loader2,
    file: File,
    search: Search,
    arrowUpFromLine: ArrowUpFromLine,
    arrowDownFromLine: ArrowDownFromLine,
    arrowRightLeft: ArrowRightLeft,
    chevronsUpDown: ChevronsUpDown,
    check: Check
};
